# Night Fade is developed and maintained by Jesai Tarun.
# If you've found value in it, your support would mean the world and would help me continue active development. Thank you!

buy_me_a_coffee: jesaitarun
